### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by imSunnyk** [KushalVijay/My-Smart-Buy#1]
Could you plz help to run this project?
Plz provide required packages and steps for it?

**Comment by KushalVijay** [comment]
Hey!
Actually, When I created this project I used the global packages installed in my PC for my virtual environment.
You have 2 options to solve this issue :
1. ) Either try to run the like any other Django project and solve the errors step by step by installing missing modules.
2.) I'm attaching the requirements.txt file but it includes global site-packages installed in my PC.

Hope it'll help.

**Comment by imSunnyk** [comment]
Hi kushal,

You were going to add requirements.txt....

Plz add or attach in comment

**Comment by KushalVijay** [comment]
absl-py==0.8.0
aenum==2.2.3
astor==0.8.0
astroid==2.2.5
atomicwrites==1.3.0
attrs==19.2.0
awscli==1.17.9
backcall==0.1.0
beautifulsoup4==4.6.3
bleach==3.1.0
blis==0.2.4
boto==2.49.0
boto3==1.9.215
botocore==1.14.9
bs4==0.0.1
cachetools==3.1.1
catalogue==1.0.0
certifi==2018.10.15
chardet==3.0.4
ChatterBot==1.0.5
colorama==0.4.1
conllu==2.2.1
cycler==0.10.0
cymem==2.0.2
cytoolz==0.10.0
decorator==4.4.0
defusedxml==0.6.0
dj-database-url==0.5.0
Django==1.11.17
django-crispy-forms==1.7.2
django-filter==2.2.0
django-forms-bootstrap==3.1.0
django-heroku==0.3.1
django-hosts==3.0
django-mysql==3.0.0.post1
djangorestframework==3.10.3
docutils==0.15.2
entrypoints==0.3
funcy==1.13
future==0.18.0
fuzzywuzzy==0.17.0
gast==0.2.2
google-pasta==0.1.7
grpcio==1.23.0
h5py==2.10.0
idna==2.7
importlib==1.0.4
importlib-metadata==0.23
inflection==0.3.1
ipykernel==5.1.3
ipython==7.9.0
ipython-genutils==0.2.0
ipywidgets==7.5.1
isort==4.3.21
jedi==0.15.1
jellyfish==0.7.2
Jinja2==2.10.3
jmespath==0.9.4
joblib==0.13.2
json5==0.8.5
jsonschema==3.2.0
kiwisolver==1.1.0
lazy-object-proxy==1.4.1
lxml==4.3.4
Markdown==3.1.1
MarkupSafe==1.1.1
mathparse==0.1.2
mccabe==0.6.1
mistune==0.8.4
more-itertools==7.0.0
murmurhash==1.0.2
mysql-connector-python==8.0.17
mysqlclient==1.4.2.post1
nbconvert==5.6.1
nbformat==4.4.0
networkx==2.3
nmslib==2.0.5
normalise==0.1.8
notebook==6.0.2
numexpr==2.7.0
opt-einsum==3.1.0
packaging==19.2
pandocfilters==1.4.2
parso==0.5.1
pickleshare==0.7.5
Pillow==5.4.1
Pint==0.11
pipenv==2018.11.26
plac==0.9.6
pluggy==0.13.0
pprint==0.1
preshed==2.0.1
prometheus-client==0.7.1
prompt-toolkit==2.0.10
protobuf==3.9.1
psutil==5.6.7
psycopg2==2.8.2
py==1.8.0
pyasn1==0.4.8
pyasn1-modules==0.2.7
pybind11==2.3.0
pyemd==0.5.1
Pygments==2.4.2
pyHook==1.5.1
pyLDAvis==2.1.2
pylint==2.3.1
pymongo==3.10.1
pyparsing==2.4.2
Pyphen==0.9.5
pypiwin32==223
pyrsistent==0.15.6
pysbd==0.2.3
PySocks==1.7.1
pytest==5.2.1
python-dateutil==2.7.5
pytz==2018.7
pywin32==223
pywinpty==0.5.5
PyYAML==5.1.2
pyzbar==0.1.8
pyzmq==18.1.1
qtconsole==4.6.0
regex==2020.1.8
requests==2.20.0
requests-oauthlib==1.2.0
roman==3.2
rsa==3.4.2
s3transfer==0.3.2
selenium==3.141.0
Send2Trash==1.5.0
six==1.12.0
smart-open==1.8.4
SQLAlchemy==1.2.19
squarify==0.4.3
srsly==0.1.0
stripe==2.32.1
syntok==1.2.2
tabulate==0.8.3
tem-py==1.3.0
termcolor==1.1.0
terminado==0.8.3
testpath==0.4.4
thinc==7.0.8
threadsafe-tkinter==1.0.1
toolz==0.10.0
torch==1.0.1
tornado==6.0.3
tqdm==4.35.0
traitlets==4.3.3
tweepy==3.8.0
typed-ast==1.4.0
umap==0.1.1
urllib3==1.24
virtualenv==16.6.0
virtualenv-clone==0.5.3
wasabi==0.6.0
wcwidth==0.1.7
webencodings==0.5.1
Werkzeug==0.15.6
whitenoise==4.1.2
widgetsnbextension==3.5.1
wikipedia==1.4.0
wrapt==1.11.2
xlrd==1.2.0
zipp==0.6.0
